services:

  proxy:
    image: nginx:1.21.6-alpine
    container_name: proxy
    volumes:
      - ./proxy:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
    networks:
      - internal_net

  authentication_service:
    build: authentication_service
    container_name: authentication_service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    command: java -jar target/authentication_service.jar
    networks:
      - internal_net

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672" # management UI
      - "5672:5672"   # AMQP protocol
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - internal_net

  api_gateway:
    build: api_gateway
    restart: always
    ports:
      - "8084:80"
    command: java -jar target/api_gateway.jar
    networks:
      - internal_net

  frontend:
    build: frontend
    container_name: frontend
    depends_on:
      - proxy
    networks:
      - internal_net

networks:
  internal_net:
    name: rsww_180429_internal
    driver: overlay
    attachable: true

