services:
  authentication_service:
    build: authentication_service
    container_name: authentication_service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    command: java -jar target/authentication_service.jar
    networks:
      - internal_net

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672" # management UI
      - "5672:5672"   # AMQP protocol
    networks:
      - internal_net

  api_gateway:
    build: api_gateway
    container_name: api_gateway
    restart: always
    ports:
      - "8082:8082"
    command: java -jar target/api_gateway.jar
    networks:
      - internal_net

  fronted:
    build: fronted
    container_name: fronted
    restart: always
    ports:
      - "8083:8083"
    networks:
      - internal_net

networks:
  internal_net:
    name: rsww_180429_internal
    driver: overlay
    attachable: true

